### ISSUE TITLE
NameError: name 'language' is not defined

### ISSUE THREAD

**Issue by Stragis** [terrorbox/zendesk-macro-backup#1]
>>> 
 RESTART: C:\Users\xxx\Desktop\zendesk-macro-backup-master\make_macro_backup.py 
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\zendesk-macro-backup-master\make_macro_backup.py", line 15, in <module>
    backup_path = os.path.join(str(date), language)
NameError: name 'language' is not defined
>>>

**Comment by Stragis** [comment]
Removing the language argument and the script runs.

**Comment by terrorbox** [comment]
Thank you! Fixed in https://github.com/terrorbox/zendesk-macro-backup/commit/cec7790c46348c5d1674abf7a29c359fa38b8a82.
